name: FNPC
main: net.FENGberd.Nukkit.FNPC.Main
version: "2.0"
api: ["1.0.0"]
author: "FENGberd, PetteriM1"
description: "A simple NPC plugin"
permissions:
 FNPC.*:
  description: " "
  default: op
 FNPC.command.*:
  description: " "
  default: op
 FNPC.command.fnpc:
  description: " "
  default: op
